package com.xml.team18.poverenik.soap.resenje;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T20:41:16.356+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ResenjeService", 
                  wsdlLocation = "file:/C:/Users/gh/Desktop/xmlProjekat/xml2020/poverenik/src/main/resources/wsdl/resenje.wsdl",
                  targetNamespace = "http://resenje.soap.poverenik.team18.xml.com/") 
public class ResenjeService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://resenje.soap.poverenik.team18.xml.com/", "ResenjeService");
    public final static QName ResenjeServiceSoapBinding = new QName("http://resenje.soap.poverenik.team18.xml.com/", "ResenjeServiceSoapBinding");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/gh/Desktop/xmlProjekat/xml2020/poverenik/src/main/resources/wsdl/resenje.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ResenjeService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/gh/Desktop/xmlProjekat/xml2020/poverenik/src/main/resources/wsdl/resenje.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ResenjeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ResenjeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResenjeService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ResenjeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ResenjeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ResenjeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ResenjeServicePortType
     */
    @WebEndpoint(name = "ResenjeServiceSoapBinding")
    public ResenjeServicePortType getResenjeServiceSoapBinding() {
        return super.getPort(ResenjeServiceSoapBinding, ResenjeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResenjeServicePortType
     */
    @WebEndpoint(name = "ResenjeServiceSoapBinding")
    public ResenjeServicePortType getResenjeServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ResenjeServiceSoapBinding, ResenjeServicePortType.class, features);
    }

}
