package com.xml.team18.poverenik.soap.zalba;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-03T22:48:56.679+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ZalbaService", 
                  wsdlLocation = "src/main/resources/wsdl/zalba.wsdl",
                  targetNamespace = "http://zalba.soap.poverenik.team18.xml.com/") 
public class ZalbaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://zalba.soap.poverenik.team18.xml.com/", "ZalbaService");
    public final static QName ZalbaServiceSoapBinding = new QName("http://zalba.soap.poverenik.team18.xml.com/", "ZalbaServiceSoapBinding");
    static {
        URL url = ZalbaService.class.getClassLoader().getResource("wsdl/zalba.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ZalbaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/zalba.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public ZalbaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZalbaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZalbaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZalbaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZalbaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZalbaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZalbaServicePortType
     */
    @WebEndpoint(name = "ZalbaServiceSoapBinding")
    public ZalbaServicePortType getZalbaServiceSoapBinding() {
        return super.getPort(ZalbaServiceSoapBinding, ZalbaServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZalbaServicePortType
     */
    @WebEndpoint(name = "ZalbaServiceSoapBinding")
    public ZalbaServicePortType getZalbaServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ZalbaServiceSoapBinding, ZalbaServicePortType.class, features);
    }

}
