package com.xml.team18.sluzbenik.soap.incoming;

import com.xml.team18.sluzbenik.factory.IzvestajFactory;
import com.xml.team18.sluzbenik.model.izvestaj.Izvestaj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T17:42:51.622+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://izvestaj.soap.poverenik.team18.xml.com/", name = "IzvestajServicePortType")
@XmlSeeAlso({IzvestajFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IzvestajServicePortType {

    @WebMethod(action = "podnesiIzvestaj")
    @WebResult(name = "uspesno", targetNamespace = "http://izvestaj.soap.poverenik.team18.xml.com/", partName = "uspesno")
    boolean podnesiIzvestaj(
        @WebParam(partName = "izvestaj", name = "izvestaj")
                Izvestaj izvestaj
    );
}
