package com.xml.team18.sluzbenik.soap.incoming;

import com.xml.team18.sluzbenik.factory.ResenjeFactory;
import com.xml.team18.sluzbenik.model.ListaResenja;
import com.xml.team18.sluzbenik.model.resenje.Resenje;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-02-05T20:41:16.262+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://resenje.soap.poverenik.team18.xml.com/", name = "ResenjeServicePortType")
@XmlSeeAlso({ResenjeFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ResenjeServicePortType {

    @WebMethod(action = "getById")
    @WebResult(name = "resenje", targetNamespace = "http://resenje.soap.poverenik.team18.xml.com/", partName = "resenje")
    Resenje getById(
        @WebParam(partName = "idResenja", name = "idResenja")
        String idResenja
    );

    @WebMethod(action = "pretraga")
    @WebResult(name = "resenja", targetNamespace = "http://resenje.soap.poverenik.team18.xml.com/", partName = "resenja")
    ListaResenja pretraga(
        @WebParam(partName = "upit", name = "upit")
        String upit
    );
}
