export function xmlResenjePrihvatanje_cutanje(zalba: any, izjasnjen: boolean): string {
  return `<resenje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" rdfa_r="http://team14.xml.com/rdf/resenja" rdfa_pred="http://team14.xml.com/rdf/resenja/predicate/" tip="prihvatanje"><broj></broj><datum>${new Date().toISOString().slice(0, 10)}</datum><zalilac id="${zalba.podnosilac._attributes.id}"><adresa><mesto>${zalba.podnosilac.adresa.mesto._text}</mesto><ulica>${zalba.podnosilac.adresa.ulica._text}</ulica></adresa><ime-prezime>${zalba.podnosilac['ime-prezime']._text}</ime-prezime></zalilac><protiv><adresa><mesto>${zalba.protiv.adresa.mesto._text}</mesto><ulica>${zalba.protiv.adresa.ulica._text}</ulica></adresa><naziv>${zalba.protiv.naziv._text}</naziv></protiv><zalba id="${zalba._attributes.id}" tip="cutanje"><datum>${zalba.datum._text}</datum><nepostupanje/></zalba><zahtev id="${zalba.zahtev._attributes.id}"><datum>${zalba.zahtev.datum._text}</datum><opis-zahteva>${zalba.zahtev['opis-zahteva']._text}</opis-zahteva></zahtev><osnov></osnov><telo><nalog><akcija></akcija><obavestiti rok=""/></nalog></telo><obrazlozenje><izjasnjenje odgovor="${izjasnjen}"/><pravno-sredstvo rok="" taksa=""><sud><naziv></naziv></sud></pravno-sredstvo></obrazlozenje><poverenik><ime-prezime></ime-prezime></poverenik></resenje>`;
}


export function xmlResenjePrihvatanje_naOdluku(zalba: any, izjasnjen: boolean): string {
  return `<resenje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" rdfa_r="http://team14.xml.com/rdf/resenja" rdfa_pred="http://team14.xml.com/rdf/resenja/predicate/" tip="prihvatanje"><broj></broj><datum>${new Date().toISOString().slice(0, 10)}</datum><zalilac id="${zalba.podnosilac._attributes.id}"><adresa><mesto>${zalba.podnosilac.adresa.mesto._text}</mesto><ulica>${zalba.podnosilac.adresa.ulica._text}</ulica></adresa><ime-prezime>${zalba.podnosilac['ime-prezime']._text}</ime-prezime></zalilac><protiv><adresa><mesto>${zalba.protiv.donosilac.adresa.mesto._text}</mesto><ulica>${zalba.protiv.donosilac.adresa.ulica._text}</ulica></adresa><naziv>${zalba.protiv.donosilac.naziv._text}</naziv></protiv><zalba id="${zalba._attributes.id}" tip="na-odluku"><datum>${zalba.datum._text}</datum><obavestenje id="${zalba.protiv._attributes.id}"><broj-obavestenja>${zalba.protiv['broj-obavestenja']._text}</broj-obavestenja><datum-obavestenja>${zalba.protiv.datum._text}</datum-obavestenja></obavestenje></zalba><zahtev id="${zalba.zahtev._attributes.id}"><datum>${zalba.zahtev.datum._text}</datum><opis-zahteva>${zalba.zahtev['opis-zahteva']._text}</opis-zahteva></zahtev><osnov></osnov><telo><nalog><akcija></akcija><obavestiti rok=""/></nalog></telo><obrazlozenje><izjasnjenje odgovor="${izjasnjen}"/><pravno-sredstvo rok="" taksa=""><sud><naziv></naziv></sud></pravno-sredstvo></obrazlozenje><poverenik><ime-prezime></ime-prezime></poverenik></resenje>`;
}

export function xmlResenjeOdbijanje_cutanje(zalba: any, izjasnjen: boolean): string {
  return `<resenje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" rdfa_r="http://team14.xml.com/rdf/resenja" rdfa_pred="http://team14.xml.com/rdf/resenja/predicate/" tip=""><broj></broj><datum>${new Date().toISOString().slice(0, 10)}</datum><zalilac id="${zalba.podnosilac._attributes.id}"><adresa><mesto>${zalba.podnosilac.adresa.mesto._text}</mesto><ulica>${zalba.podnosilac.adresa.ulica._text}</ulica></adresa><ime-prezime>${zalba.podnosilac['ime-prezime']._text}</ime-prezime></zalilac><protiv><adresa><mesto>${zalba.protiv.adresa.mesto._text}</mesto><ulica>${zalba.protiv.adresa.ulica._text}</ulica></adresa><naziv>${zalba.protiv.naziv._text}</naziv></protiv><zalba id="${zalba._attributes.id}" tip="cutanje"><datum>${zalba.datum._text}</datum><nepostupanje/></zalba><zahtev id="${zalba.zahtev._attributes.id}"><datum>${zalba.zahtev.datum._text}</datum><opis-zahteva>${zalba.zahtev['opis-zahteva']._text}</opis-zahteva></zahtev><osnov></osnov><telo><odbijanje/></telo><obrazlozenje><izjasnjenje odgovor="${izjasnjen}"/><pravno-sredstvo rok="" taksa=""><sud><naziv></naziv></sud></pravno-sredstvo></obrazlozenje><poverenik><ime-prezime></ime-prezime></poverenik></resenje>`;
}

export function xmlResenjeOdbijanje_naOdluku(zalba: any, izjasnjen: boolean): string {
  return `<resenje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" rdfa_r="http://team14.xml.com/rdf/resenja" rdfa_pred="http://team14.xml.com/rdf/resenja/predicate/" tip=""><broj></broj><datum>${new Date().toISOString().slice(0, 10)}</datum><zalilac id="${zalba.podnosilac._attributes.id}"><adresa><mesto>${zalba.podnosilac.adresa.mesto._text}</mesto><ulica>${zalba.podnosilac.adresa.ulica._text}</ulica></adresa><ime-prezime>${zalba.podnosilac['ime-prezime']._text}</ime-prezime></zalilac><protiv><adresa><mesto>${zalba.protiv.donosilac.adresa.mesto._text}</mesto><ulica>${zalba.protiv.donosilac.adresa.ulica._text}</ulica></adresa><naziv>${zalba.protiv.donosilac.naziv._text}</naziv></protiv><zalba id="${zalba._attributes.id}" tip="na-odluku"><datum>${zalba.datum._text}</datum><obavestenje id="${zalba.protiv._attributes.id}"><broj-obavestenja>${zalba.protiv['broj-obavestenja']._text}</broj-obavestenja><datum-obavestenja>${zalba.protiv.datum._text}</datum-obavestenja></obavestenje></zalba><zahtev id="${zalba.zahtev._attributes.id}"><datum>${zalba.zahtev.datum._text}</datum><opis-zahteva>${zalba.zahtev['opis-zahteva']._text}</opis-zahteva></zahtev><osnov></osnov><telo><odbijanje/></telo><obrazlozenje><izjasnjenje odgovor="${izjasnjen}"/><pravno-sredstvo rok="" taksa=""><sud><naziv></naziv></sud></pravno-sredstvo></obrazlozenje><poverenik><ime-prezime></ime-prezime></poverenik></resenje>`;
}
